name: .NET Core build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: ./PreMailer.Net
      run: dotnet restore
    - name: Build
      working-directory: ./PreMailer.Net
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./PreMailer.Net
      run: dotnet test --no-restore --verbosity normal --collect "Code coverage"

    # Publish
    - name: publish on version change
      if: ${{ github.event_name == 'release' }}
      # This should use the GITHUB_TOKEN to do the actual publish, rather than needing a secret
      run: |
        dotnet nuget add source --username agrande-ea --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/eventsair/index.json"

        dotnet build --configuration Release

        dotnet pack PreMailer.Net\PreMailer.Net.csproj --configuration Release --include-symbols

        dotnet nuget push "bin/Release/Premailer.Net.2.7.0-beta.nupkg" --source "github"
